//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CURSO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_CURSO()
        {
            this.TB_ESTUDIANTEXCURSO = new HashSet<TB_ESTUDIANTEXCURSO>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public Nullable<int> horasCredito { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ESTUDIANTEXCURSO> TB_ESTUDIANTEXCURSO { get; set; }
    }
}
