//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ESTUDIANTEXCURSO
    {
        public int estudiante_id { get; set; }
        public int curso_id { get; set; }
        public string semestre { get; set; }
        public Nullable<int> añoAcademico { get; set; }
        public Nullable<int> grado { get; set; }
    
        public virtual TB_CURSO TB_CURSO { get; set; }
        public virtual TB_ESTUDIANTE TB_ESTUDIANTE { get; set; }
    }
}
